test_anagram (__main__.TestExercice) ... ERROR
test_doubles (__main__.TestExercice) ... FAIL
test_frequence (__main__.TestExercice) ... FAIL
test_grades (__main__.TestExercice) ... FAIL
test_order (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 35, in test_anagram
    output = [exercice.anagrams(v) for v in words]
  File "test_exercice.py", line 35, in <listcomp>
    output = [exercice.anagrams(v) for v in words]
  File "/home/runner/work/2021a-c01-ch6-1-exercices-YuliiaOz/2021a-c01-ch6-1-exercices-YuliiaOz/exercice.py", line 21, in anagrams
    chaine1 = list(input())
EOFError: EOF when reading a line

======================================================================
ERROR: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 19, in test_order
    output = [exercice.order(v) for v in values]
  File "test_exercice.py", line 19, in <listcomp>
    output = [exercice.order(v) for v in values]
  File "/home/runner/work/2021a-c01-ch6-1-exercices-YuliiaOz/2021a-c01-ch6-1-exercices-YuliiaOz/exercice.py", line 11, in order
    liste_de_valeurs.sort()
UnboundLocalError: local variable 'liste_de_valeurs' referenced before assignment

======================================================================
FAIL: test_doubles (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 52, in test_doubles
    self.assertListEqual(
AssertionError: Lists differ: [True, True] != [False, True]

First differing element 0:
True
False

- [True, True]
+ [False, True] : Erreur dans les doublons

======================================================================
FAIL: test_frequence (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 80, in test_frequence
    self.assertListEqual(
AssertionError: Lists differ: [{}, {}] != [{'B': 1, 'o': 4, 'n': 2, 'j': 2, 'u': 2, '[188 chars]: 1}]

First differing element 0:
{}
{'B': 1, 'o': 4, 'n': 2, 'j': 2, 'u': 2, 'r': 2, ',': 1, ' ': 1, 'b': 1}

- [{}, {}]
+ [{' ': 1, ',': 1, 'B': 1, 'b': 1, 'j': 2, 'n': 2, 'o': 4, 'r': 2, 'u': 2},
+  {' ': 5,
+   "'": 1,
+   '/': 1,
+   'J': 1,
+   'a': 6,
+   'b': 1,
+   'c': 3,
+   'd': 1,
+   'e': 7,
+   'f': 1,
+   'g': 2,
+   'i': 5,
+   'l': 3,
+   'm': 2,
+   'n': 4,
+   'o': 4,
+   'q': 1,
+   'r': 3,
+   't': 2,
+   'u': 2}] : Erreur dans les histogrammes

======================================================================
FAIL: test_grades (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_grades
    self.assertDictEqual(
AssertionError: {} != {'Sam': 85}
- {}
+ {'Sam': 85} : Erreur dans les notes

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3, errors=2)
